
.PHONY : clean
clean:
	-rm -rf img*
	-rm *.out
	-rm *.png
	-rm microturbulence.inp
	-rm numberdens_co.inp
	-rm gas_temperature.inp
	-rm gas_velocity.inp
	-rm amr_grid.inp
	-rm lines.inp
	-rm molecule_co.inp
	-rm camera_wavelength_micron.inp
	-rm radmc3d.out
	-rm spectrum.out
	-rm *.mem
